CREATE INDEX [IX_LINEITEM_L_SHIPDATE_A14C3] ON [TCP-H].[TPCSOURCE].[LINEITEM] ([L_SHIPDATE]) INCLUDE ([L_QUANTITY], [L_EXTENDEDPRICE], [L_DISCOUNT], [L_TAX], [L_RETURNFLAG], [L_LINESTATUS])
CREATE INDEX [IX_PART_P_SIZE_C0C90] ON [TCP-H].[TPCSOURCE].[PART] ([P_SIZE]) INCLUDE ([P_MFGR], [P_TYPE])
CREATE INDEX [IX_ORDERS_O_ORDERDATE_9C4B0] ON [TCP-H].[TPCSOURCE].[ORDERS] ([O_ORDERDATE]) INCLUDE ([O_ORDERPRIORITY])
CREATE INDEX [IX_ORDERS_O_ORDERDATE_5A81B] ON [TCP-H].[TPCSOURCE].[ORDERS] ([O_ORDERDATE]) INCLUDE ([O_CUSTKEY])
CREATE INDEX [IX_LINEITEM_L_QUANTITY_L_DISCOUNT_L_SHIPDATE_5030A] ON [TCP-H].[TPCSOURCE].[LINEITEM] ([L_QUANTITY], [L_DISCOUNT], [L_SHIPDATE]) INCLUDE ([L_EXTENDEDPRICE])
CREATE INDEX [IX_ORDERS_O_CUSTKEY_1D178] ON [TCP-H].[TPCSOURCE].[ORDERS] ([O_CUSTKEY])
CREATE INDEX [IX_LINEITEM_L_PARTKEY_34CDE] ON [TCP-H].[TPCSOURCE].[LINEITEM] ([L_PARTKEY]) INCLUDE ([L_SUPPKEY], [L_QUANTITY], [L_EXTENDEDPRICE], [L_DISCOUNT])
CREATE INDEX [IX_LINEITEM_L_RETURNFLAG_C58D9] ON [TCP-H].[TPCSOURCE].[LINEITEM] ([L_RETURNFLAG]) INCLUDE ([L_EXTENDEDPRICE], [L_DISCOUNT])

drop INDEX [IX_LINEITEM_L_SHIPDATE_A14C3] ON [TCP-H].[TPCSOURCE].[LINEITEM] 
drop INDEX [IX_PART_P_SIZE_C0C90] ON [TCP-H].[TPCSOURCE].[PART] 
drop INDEX [IX_ORDERS_O_ORDERDATE_9C4B0] ON [TCP-H].[TPCSOURCE].[ORDERS] 
drop INDEX [IX_ORDERS_O_ORDERDATE_5A81B] ON [TCP-H].[TPCSOURCE].[ORDERS] 
drop INDEX [IX_LINEITEM_L_QUANTITY_L_DISCOUNT_L_SHIPDATE_5030A] ON [TCP-H].[TPCSOURCE].[LINEITEM] 
drop INDEX [IX_ORDERS_O_CUSTKEY_1D178] ON [TCP-H].[TPCSOURCE].[ORDERS] 
drop INDEX [IX_LINEITEM_L_PARTKEY_34CDE] ON [TCP-H].[TPCSOURCE].[LINEITEM]
drop INDEX [IX_LINEITEM_L_RETURNFLAG_C58D9] ON [TCP-H].[TPCSOURCE].[LINEITEM] 

create index [IX_Customer] on [TCP-H].[TPCSOURCE].[CUSTOMER] (C_Name)
create index [IX_LINEITEM] on [TCP-H].[TPCSOURCE].[LINEITEM] (L_SHIPDATE)
create index [IX_NATION] on [TCP-H].[TPCSOURCE].[NATION] (N_Name)
create index [IX_ORDERS] on [TCP-H].[TPCSOURCE].[ORDERS] (O_Orderdate)
create index [IX_PART] on [TCP-H].[TPCSOURCE].[PART] (P_Name)
create index [IX_PARTSUPP] on [TCP-H].[TPCSOURCE].[PARTSUPP] (PS_AVAILQTY)
create index [IX_REGION] on [TCP-H].[TPCSOURCE].[REGION] (R_Name)
create index [IX_SUPPLIER] on [TCP-H].[TPCSOURCE].[SUPPLIER] (S_Name)

drop index [IX_Customer] on [TCP-H].[TPCSOURCE].[CUSTOMER] 
drop index [IX_LINEITEM] on [TCP-H].[TPCSOURCE].[LINEITEM] 
drop index [IX_NATION] on [TCP-H].[TPCSOURCE].[NATION] 
drop index [IX_ORDERS] on [TCP-H].[TPCSOURCE].[ORDERS] 
drop index [IX_PART] on [TCP-H].[TPCSOURCE].[PART] 
drop index [IX_PARTSUPP] on [TCP-H].[TPCSOURCE].[PARTSUPP] 
drop index [IX_REGION] on [TCP-H].[TPCSOURCE].[REGION] 
drop index [IX_SUPPLIER] on [TCP-H].[TPCSOURCE].[SUPPLIER] 